# Generated by Django 4.2.11 on 2026-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('LOAN_REPAYMENT', 'Loan Repayment')], default='DEPOSIT', max_length=20),
        ),
    ]
