# Generated by Django 4.2.11 on 2026-06-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_loan_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_interest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
