# Generated by Django 4.2.11 on 2026-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_loan_last_interest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('INTEREST', 'Interest Accrual')], default='DEPOSIT', max_length=20),
        ),
    ]
