# Generated by Django 4.2.11 on 2026-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_profile_address_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
